import Head from "next/head";
import Image from "next/image";
import Input from "../components/input";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  const handleClick = (e) => {
    e.preventDefault();
    router.push("about");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>test recoil</h1>
        <Input />

        <a onClick={handleClick}>about</a>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
